### ISSUE TITLE
fips_ciphers - nil:NilClass 

### ISSUE THREAD

**Issue by RoshanPanpaliya** [simp/pupmod-simp-simp_grafana#28]
Hi,
we are using this module v3.4.0 and its working fine if openssl is installed on the system. But if its not installed then giving below error message for fact fips_ciphers. 
Puppet version 2016.4.6
Error: Facter: error while resolving custom fact "fips_ciphers": undefined method `split' for nil:NilClass 

If we can put condition on facter on openssl then we can avoid this error

**Comment by nick-markowski** [comment]
Hey Roshan, I have opened a bug https://simp-project.atlassian.net/browse/SIMP-3490

Thank you for the feedback!

**Comment by nick-markowski** [comment]
Hey Roshan, the fact has been updated and should no longer be an issue. Thanks again.

**Comment by RoshanPanpaliya** [comment]
Thanks Nick, In which version of simp-simplib this bug is fixed. which versin should we use?

**Comment by nick-markowski** [comment]
Hey, the fix is currently in master.  We plan to release in the next few weeks, and this fix will be part of it.
